var greeting = "hallo world";
console.log(greeting);
var discount = 10;
var discount = 100;
console.log(discount);
console.log(a);
var a = "halo";
const halo = "halo";
console.log(halo);
console.log(typeof NaN);
console.log(typeof null);
console.log(typeof undefined);
const bilangan = NaN;
console.log(typeof bilangan);
const txt = "hallo";
console.log(txt.slice(0,3));
console.log(txt.substring(1,0));
